# Generated by Django 3.2.12 on 2025-05-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userfolder_userfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='user',
        ),
    ]
